name: Auto-assign Reviewers

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['hoangsonww', 'kailielexx']
            })
          token: ${{ secrets.GITHUB_TOKEN }}
